# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49061b49e57a84dc3102012f7d482aa27cc6c61b4d3f3dbcc29f1b02a789f8633de0de8a5a9ca5023568cd1f0c3e6c1aababc06a3dfb0701a0b0f6ce226efc1a

test:
  secret_key_base: 5f1d2786e21b5ce14cfff877bcff186469f318257a4c35d70141dd54172769ac46f63249103662adbc9719584305a5b7543b2ee6687403494ad639d7266e9165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
